### ISSUE TITLE
Zeex's Compiler

### ISSUE THREAD

**Issue by Lathrel** [Southclaws/sampctl#101]
This is compatible with zeex's compile?

**Comment by Dayvison** [comment]
actually this only use the zeex compiler

**Comment by Lathrel** [comment]
Thanks.
but YSI don't work with this for me.

**Comment by Lathrel** [comment]
@Dayvison Can send me your builds "args": [ ] inside pawn.json?

**Comment by Dayvison** [comment]
Here all working fine, this could be a error in your script.

Simple tests:
```
mkdir test_ysi && cd test_ysi
echo -e "{\n\t\"entry\": \"test.pwn\",\n\t\"output\": \"test.amx\",\n\t\"dependencies\": [\n\t\t\"sampctl/samp-stdlib\",\n\t\\t\"pawn-lang/YSI-Includes\"\n\t]\n}\n" > pawn.json
echo -e "#include \"YSI\\y_utils\"\n#include \"YSI\\y_iterate\"\n#include \"YSI\\y_hooks\"\n#include \"YSI\\y_inline\"\n\nmain()\n{\n\t\n}" > test.pwn
sampctl package build --forceEnsure
```

**Comment by Lathrel** [comment]
this is correct?

"args": [
				"-d3"
			]

If I only use this I get that's erros.

**Comment by Dayvison** [comment]
I think recently Y_Less made ysi work without any pawn arguments, but i use theese
```yaml
    args: 
      - "-;+"
      - "-(+"
      - "-\\+"
      - "-d3"
```

**Comment by Southclaws** [comment]
sampctl uses a default build config which [looks like this](https://github.com/Southclaws/sampctl/blob/63e9e468221b1a919ee4b8ee7ea53efca1c180b6/types/compiler.go#L22-L24).

However, as soon as you add an `args` field to a build, the default is dropped completely - not "merged" with your settings.

So, if you want to *add* args to the defaults, you must also specify the defaults explicitly.

It's like this because you might want to perform a build with no args at all, in which case you'd simply add `"args": []`. I have spotted a couple of bugs in the code though so I will resolve those and update the documentation.

Docs: https://github.com/Southclaws/sampctl/wiki/Package-Definition-Reference#builds
