### ISSUE TITLE
Add option to create code documentation

### ISSUE THREAD

**Issue by BigETI** [Southclaws/sampctl#106]
Library developers should have an easily accessible option to generate code documentation.
Reference: http://forum.sa-mp.com/showthread.php?t=381784

**Comment by Y-Less** [comment]
They do: `-r`.

**Comment by Y-Less** [comment]
```
  "builds": [{
    "name": "default"
  }, {
    "name": "documentation",
    "args": [ "-;+", "-(+", "-Z+", "-\\+", "-r" ]
  }]
```

**Comment by BigETI** [comment]
This is not a default option for pawn.json or pawn.yaml when initializing a package.
Additionally it should add pawndoc.xls (see forum thread) to have a decent code documentation view from a browser.

**Comment by Southclaws** [comment]
I actually plan to implement a documentation system much like that of Go's `godoc` tool.

I honestly find the XML syntax *wayyy* too pedantic and over-specific. I like the minimal approach of Go documentation, it doesn't require you specify every parameter with XML syntax, it's just a nice simple comment block above each function so [this](https://github.com/Southclaws/sampctl/blob/master/rook/ensure.go#L103-L106) turns into [this](https://godoc.org/github.com/Southclaws/sampctl/rook#EnsurePackage).

It's not a default because I rarely see docstrings in the wild. I personally never used them due to the annoying syntax and I prefer to just read source code comments than open a web browser anyway (and, I also find the XML syntax makes reading source code comments extra irritating). And as Y_Less said, you can simply add the `-r` option to a build.

The doc generator will be in once the pawn-parser project can easily pick out comments and functions so it can easily infer documentation comments for functions, enumerators and constants.

**Comment by Dayvison** [comment]
I agree with Southclaws about the xml, this is how i documentate the pawn code
![img](https://i.imgur.com/VJ3aFxV.png)

I'm writing a python script to parse the xml report generated by pawn compiler, and export the documentation to a static html page, with a better desing than pawndoc.xsl
