### ISSUE TITLE
Automated Packaging for Releases

### ISSUE THREAD

**Issue by Y-Less** [Southclaws/sampctl#129]
That's how you release sampctl versions, could it do the same for pawn libraries?

**Comment by Southclaws** [comment]
I've considered building a similar tool for Pawn, yes - built into sampctl.

Currently git tags are used for versioning but some GitHub integration to automatically create releases with changelogs could be useful.

What kind of ideas did you have in mind? GoReleaser is a bit of a different use-case because it's designed to deliver compiled binaries to end-users whereas Pawn users most likely want package sources for their own builds.

**Comment by Y-Less** [comment]
Basicaly exactly what you just said about tagging releases.  Especially packaging, for example, YSI 5.x has about 5 external dependencies, so it would be nice to have them all bundled together in a standardised "pawno/includes" structure automatically and released like that.  Then people who don't use samplctl can just download the whole thing at once.

**Comment by Southclaws** [comment]
Ah okay, so kind of like Python's locking/freezing - this should be a trivial feature to implement.

**Comment by Southclaws** [comment]
I've had more thought on this and here's a proposal:

One of the main problems I've noticed with software versioning is that it's easy to forget - I do this all the time! There are countless npm projects with a version of `0.1.0` because this is the default that `npm init` sets and it often gets forgotten.

While working as a Go dev, I devised a kind of hacky versioning method that involved keeping a file named `VERSION` in my working dir. When I released a new version, I'd manually change the value in there and then run a `make` command (`make version` or something) which would run:
- `git tag $(cat VERSION)`
- `git push $(cat VERSION)`
The problem here is it's not cross-platform unless you have some kind of linux toolset on windows. This method leaked into my sampctl workflow and it's not really easily usable by other people even though the git tag is the most important part of Pawn package versioning.

Doing this manually, without the make command would require remembering/checking what the *current* version is then thinking about how your commits have altered that - unnecessary brain work!

This proposal is for a `sampctl package release` which will handle:

- Asking the user for a version from a list of automatically generated versions based on the current git tag (if any).
  - If the current version is 0.1.1, the options would be:
    - `0.1.2 - I made backwards-compatible bug fixes`
    - `0.2.0 - I added functionality in a backwards-compatible manner`
    - `1.0.0 - I made incompatible API changes`
  - If the current version is 1.2.3, the options would be:
    - `1.2.4 - Patch version: backwards-compatible bug fixes`
    - `1.3.0 - I added functionality in a backwards-compatible manner`
    - `2.0.0 - I made incompatible API changes`
- (optionally) creating a release on GitHub using the API using the commits since the last tag as a changelog text
- (optionally) packaging the release to include dependencies locked at their specified versions, in a `pawno/include` folder structure, ready for drag-and-drop for non-sampctl ~peasants~ users.

**Comment by Southclaws** [comment]
quick prototype of the release tool:

![2018-03-27_12-53-32](https://user-images.githubusercontent.com/1636971/37965731-faedc974-31bd-11e8-8359-7c37f1c3841a.gif)

**Comment by Y-Less** [comment]
Nice.  Could this be written to a file, like generate:

```pawn
#define SAMCTL_VERSION_MAJOR (2)
#define SAMCTL_VERSION_MINOR (32)
#define SAMCTL_VERSION_BUILD (1331)
```

?

**Comment by Southclaws** [comment]
Ah yes, that would be useful too! That would be pretty simple.

So just to reiterate for clarity: it outputs a file named `version.inc` with that exact structure - and maybe a comment warning users not to modify the file by hand and to use sampctl instead.

```pawn
// This file was generated by `sampctl package release`
// DO NOT EDIT THIS FILE MANUALLY!

#define VERSION_MAJOR (2)
#define VERSION_MINOR (1)
#define VERSION_PATCH (13)
```

I've opted for the word "patch" given that semver.org refers to it as this and that's the site I always link to regarding versioning with sampctl.

I also removed the `SAMPCTL_` prefix because 1. the name "sampctl" may change for some future reason (pawnctl? ;) 2. I'd prefer to keep references and side effects of sampctl out of source code to make ejecting from the ecosystem or changing in future easier for users.

However I realised that it's common for libraries to use `VERSION_MAJOR` etc, so this could actually be an uppercase of the `repo` name from the package definition, for example `Southclaws/samp-ini` becomes: `SAMP_INI_VERSION_MAJOR` or `SAMPINI_VERSION_MAJOR`.

The `ensure` process could also make sure this file is in-sync with the git tag too, adjusting it if necessary (maybe the user added a tag on another remote/local or manually).

**Comment by Y-Less** [comment]
It would probably need a prefix, especially if dependencies use the same thing (in which case, the filename may need a prefix as well).  `PATCH` seems better than `BUILD` (though I do wish there was also a way to generate build numbers).

**Comment by Southclaws** [comment]
I decided against doing packaged releases with dependencies, it would lead back to the old culture of distributing all your outdated libraries with a release. I'd rather focus on making more attractive features and helping users adopt sampctl than catering to the old ways.

**Comment by Southclaws** [comment]
I actually had another idea for this, and it was inspired by YSI's version check!

Currently, `sampctl package release` will generate/update a file with the following contents:

```pawn
// This file was generated by "sampctl package release"
// DO NOT EDIT THIS FILE MANUALLY!
// To update the version number for a new release, run "sampctl package release"

#define PAWN_CHRONO_VERSION_MAJOR (1)
#define PAWN_CHRONO_VERSION_MINOR (1)
#define PAWN_CHRONO_VERSION_PATCH (0)
```

This file isn't really used for much at the moment, users can manually include this if they want for version checks, for example:

```pawn
#include <pawn_chrono_version>
#if PAWN_CHRONO_VERSION_MAJOR != 1
#error This script requires pawn-chrono version 1.x
#endif
```

It would be neat to also generate a runtime version check:

```pawn
// This file was generated by "sampctl package release"
// DO NOT EDIT THIS FILE MANUALLY!
// To update the version number for a new release, run "sampctl package release"

#define PAWN_CHRONO_VERSION_MAJOR (1)
#define PAWN_CHRONO_VERSION_MINOR (1)
#define PAWN_CHRONO_VERSION_PATCH (0)

// This would in reality be hooked and also checked for FILTERSCRIPT etc.
// but this is just a quick example
public OnGameModeInit() {
    HTTP(
        0,
        HTTP_GET,
        "http://list.packages.sampctl.com/Southclaws/pawn-chrono/version",
        "",
        "sampctl_onVersionCheck"
    );
}

forward sampctl_onVersionCheck(index, response_code, data[]);
public sampctl_onVersionCheck(index, response_code, data[]) {
    // maybe `data` can be octet-stream of three bytes: major, minor, patch
    // now the code can check if the version is below the current and if so
    // print a small information message in the console.
}
```

**Comment by spacemud** [comment]
I like it!

Another idea: would it be possible/appropriate for a definition containing the Git commit hash of the latest build to be included in this file? I find embedding this somewhere in my gamemode helps me identify the exact version where a bug might be introduced. I realise a similar thing could be achieved using Git tags/`sampctl package release`, but I'm not exactly diligent with versioning my gamemode... 😛

**Comment by Southclaws** [comment]
Yeah that's definitely possible, I could make `sampctl package release` embed a git commit hash into this file.

I do understand that versioning gamemodes is quite different to versioning libraries though, the [semantic versioning](https://semver.org) spec doesn't really fit user-facing codebases like gamemodes, websites and GUI applications.

There is also `--buildFile` on `sampctl package build` which writes an incrementing build number into a file on build. That could also be useful it it were passed into the gamemode as a definition.

The issue I have with the git hash idea is: when should that file be updated? Via `sampctl package release`? But then you have to remember another command. Via `sampctl package build` similar to `--buildFile`, maybe `--hash=gamemodes/hash.inc` then you include `hash.inc`?

I'll have a think on this, I was trying to integrate build numbers into the `package release` command but eventually gave up as I couldn't figure out a nice logical way to do it.

**Comment by Y-Less** [comment]
Is that even possible?  You need to generate the file with the hash in, for the commit you're about to make with the file with the hash in.  Is the hash the hash of the previous commit?  Is it the new commit that you haven't actually made yet?

**Comment by spacemud** [comment]
> The issue I have with the git hash idea is: when should that file be updated? Via sampctl package release? But then you have to remember another command. Via sampctl package build similar to --buildFile, maybe --hash=gamemodes/hash.inc then you include hash.inc?

Yep - that's why I questioned the appropriateness of it. It seems like a fairly niche requirement so I don't see why it couldn't be a part of the `sampctl package build` command.
