### ISSUE TITLE
conficlit in dependencies and resources(1.7.0)

### ISSUE THREAD

**Issue by Dayvison** [Southclaws/sampctl#131]
Reproduce:
```bash
mkdir issue && cd issue
echo "main() {}" > test.pwn
echo -e "{\n\t\"user\": \"none\",\n\t\"repo\": \"issue\",\n\t\"entry\": \"test.pwn\",\n\t\"output\": \"test.amx\",\n\t\"dependencies\": [\n\t\t\"sampctl/samp-stdlib\",\n\t\t\"samp-incognito/samp-streamer-plugin\"\n\t]\n}\n" > pawn.json
sampctl p ensure
sampctl p build
ERROR: Dependency include path errors found:
ERROR: Duplicate 'streamer.inc' found in both
'~/issue/dependencies/samp-streamer-plugin'
'~/issue/dependencies/samp-streamer-plugin-resource-7c00b9d8ef1afd58a2abba656afbde24/pawno/include'
```
I think there no needs to put `samp-streamer-plugin` in include paths once, they already in `resources`

**Comment by Southclaws** [comment]
This was introduced because MySQL doesn't provide includes in the repo. I'm not entirely sure what to do if includes are in both locations.

I would assume the user would desire the matching version, not the latest version so the one in `resources` should be prioritised (if natives are changed in the repo before a release, it could cause an issue).

I will try to think of an automated solution for this that won't require changing the package definition.

**Comment by Southclaws** [comment]
So far, I've resolved this by not including a package directory if it provides resources with includes. I can't think of a situation where you'd want to include files from the repo and releases.

**Comment by Dayvison** [comment]
Like i said :+1:
