### ISSUE TITLE
Resources in a separated folder

### ISSUE THREAD

**Issue by Dayvison** [Southclaws/sampctl#132]
This is a suggestion.
Put all resources in a subfolder inside dependencies. This resource folders for the same package, make navigation harder when has too much packages installed.

**Comment by Southclaws** [comment]
I was planning to do this but the issue is the dependency directory is a git repository and adding new files in there causes the git repo to flag them as changes which makes version changes and updates difficult because those files have to be removed/stashed before a fetch/merge or checkout can be performed - these happen when `ensure` is run.

**Comment by Dayvison** [comment]
What i mean:
- dependencies
    + .resources
        * samp-streamer-plugin
    + samp-streamer-plugin

**Comment by Southclaws** [comment]
Oh okay, yeah that makes sense!
