### ISSUE TITLE
sscanf warning

### ISSUE THREAD

**Issue by LashaKanteladze** [Southclaws/sampctl#155]
When I try this code `sampctl p install maddinat0r/sscanf:2.8.2` I always get this message
```
WARN: failed to ensure package github.com/maddinat0r/sscanf:2.8.2: failed to update repo state: failed to checkout necessary commit a24e2e5c796f3a4f7bab02ee5f9177b51bea1717: object not found
INFO: successfully added new dependency
```

**Comment by Southclaws** [comment]
Ah, this looks like the same issue as the streamer.

The actual release tag is `v2.8.2` - with a **v**.

I will fix this in sampctl so it uses the correct tag name instead of the one you pass after the `:` character.

For now, you can try using `sampctl p install maddinat0r/sscanf:v2.8.2` and that should work fine.
