### ISSUE TITLE
Duplicated plugins in server.cfg

### ISSUE THREAD

**Issue by n0dai** [Southclaws/sampctl#192]
Since the last update I can see many duplicated plugins in server.cfg.

For example, this is my actual server.cfg plugins part:
`plugins irc streamer FileManager bcrypt-samp sscanf mysql dns ctime mapandreas Whirlpool pawnregex crashdetect pawn-memory FileManager bcrypt-samp sscanf mysql dns ctime mapandreas Whirlpool pawnregex crashdetect pawn-memory`

**Comment by Southclaws** [comment]
Can you post your pawn.json file so I can reproduce this?

Also I've never actually attempted loading the same plugin twice on SA:MP before, does this actually cause a problem? Are plugins loaded into memory twice?

**Comment by AGraber** [comment]
I'm also experiencing this. It looks like it happens because plugin packages need this:
```
    "runtime": {
        "plugins": ["urShadow/Pawn.RakNet"]
    }
```
but adding them as dependencies already adds them as plugins. It would seem like the different "plugins" fields are getting added each other. I could be totally wrong though, just an assumption.

You can reproduce this by cloning https://github.com/AGraber/samp-037-compat, and setting local to true to the `pawn.json`. The update also seemed to break plugins for non local packages as it won't work anymore without the local function.
