### ISSUE TITLE
Add better support for SAMP Environment Variables

### ISSUE THREAD

**Issue by ADRFranklin** [Southclaws/sampctl#224]
Since I am using docker and I have to expose the port in for multiple instances, I also have then change `pawn.json` everytime I want to create a new instance or change an existing instance.

I have tried using `SAMP_PORT` as an environment in `docker-compose.yml` however it seems to have no effect and the server defaults to `:7777`

If we could have more support for these variables at runtime that would be great. it doesn't make sense to have environment files for `docker-compose.yml` and then fixed values for `pawn.json`  this also ties into #207

**Comment by Southclaws** [comment]
This might just be a documentation change, I think because `runtime` is a nested object inside `pawn.json` you need to actually export `SAMP_RUNTIME_PORT` instead of `SAMP_PORT`.

The reason being is every field in the configuration is used as an environment variable, so if there was a field in the `pawn.json` named `port` then it would be impossible to know which field the environment variable `SAMP_PORT` is targeting.

Please let me know if this works, if so, I'll update the docs.

**Comment by Southclaws** [comment]
This also means you can set *any* value in `pawn.json` via environment variables - that includes build time config!

**Comment by ADRFranklin** [comment]
Will give it a try now

**Comment by ADRFranklin** [comment]
No it did not work

**Comment by Southclaws** [comment]
Should be all good now on latest.

**Comment by Southclaws** [comment]
This should be resolved in the latest release.

Configuration now uses [Configor](https://github.com/jinzhu/configor/) to load both the sampctl config file and package definitions. So as well as supporting TOML files, you can now specify any field using environment variables.
