### ISSUE TITLE
Hang when out of disk space

### ISSUE THREAD

**Issue by Y-Less** [Southclaws/sampctl#245]
I was doing an "ensure" and during the course it filled up my disk and stopped.  I moved some files off to free up some space, but it just continued to sit there and never advanced.

**Comment by Southclaws** [comment]
I'm not entirely sure how to solve this one, it depends if the underlying filesystem API is responsible for the hang. I would have expected a full on crash from this to be honest - in fact, that would be the preferred option over hanging...

I'll look into this and see if I can reproduce inside a VM with a small disk.

**Comment by Y-Less** [comment]
I'd put this in the category of "probably can't and shouldn't be fixed" bugs - if you're out of disk space, there isn't much you can do beyond maybe report it and close.  But it is at least worth mentioning.

**Comment by Southclaws** [comment]
Yeah I'm inclined to agree - though hanging isn't really suitable behaviour, a fast exit with a relevant error would be better but I can't seem to see where the hang could occur other than `io.Read`, which is out of my control unfortunately.

But yes, worth documenting here in case someone else hits the same issue. I'll close since I can't really do anything about it.
