### ISSUE TITLE
It always shows me "exit status 3221225781"

### ISSUE THREAD

**Issue by GlowerTvg** [Southclaws/sampctl#254]
Hello, look at my problem is the following whenever I try to run or compile any package does not let me, let alone test it, I always get the error: "failed to prepare package for running: failed to compile package entry: exit status 3221225781". With both commands: "sampctl package run" and with "sampctl package build"

**Comment by Southclaws** [comment]
Post your pawn.json, it's likely an issue with the build aegs.

**Comment by GlowerTvg** [comment]
{
	"user": "RogueDrifter",
	"repo": "Anti_cheat_pack",
	"entry": "test.pwn",
	"output": "test.amx",
	"dependencies": [
		"sampctl/samp-stdlib",
		"RogueDrifter/Anti_cheat_pack",
		"pawn-lang/YSI-Includes:5.x"
	],
	"runtime": {
		"version": "0.3.7",
		"mode": "server",
		"echo": "-",
		"rcon_password": "password",
		"port": 7777,
		"hostname": "SA-MP Server",
		"maxplayers": 50,
		"language": ""
	}
}

**Comment by GlowerTvg** [comment]
https://pastebin.com/ZwDSaaPr

**Comment by GlowerTvg** [comment]
but it also sends me an error when trying to create a package with "sampctl package init", it always sends me that error, and also with the progress2 package

**Comment by Southclaws** [comment]
I'm not sure why you're seeing that error code from the compiler however I have spotted an issue with your pawn.json: you're using tag version syntax for a branch on YSI, you need to use `@` instead of `:`, see the "Dependencies" page on the wiki for information on how to specify dependency versions.

As for the actual error, run sampctl with `--verbose` and manually execute the pawncc command it outputs, there's a good chance it's just outputting the help screen and the return code is nonsense.
