### ISSUE TITLE
Support for GitLab and others

### ISSUE THREAD

**Issue by hydewhyd** [Southclaws/sampctl#266]
I have seen that the sampctl tool works with your package on github, but there is no alternative option to upload the changes to GitLab or other repositories.

I currently use a tool for GitLab in VSCode that I can upload my changes to the repository, etc.

I think it would be nice to be able to make the tool compatible with other code repositories for new projects.

The dependencies could be downloaded from github without problem.

**Comment by spacemud** [comment]
sampctl supports Git SSH URLs:

**Comment by ADRFranklin** [comment]
Though this is not related to sampctl, though is interesting to know is that Gitlab supports repository pushing. Which means you could continue to work with Gitlab and any changes that are committed to your Gitlab repo would be pushed to another git host like Github.

Just though I'd mention this. Though spacemud is correct as sampctl uses a Go implementation of the Git protocol and will handle anything related to `git pull` or `git fetch`.

**Comment by Y-Less** [comment]
That's quite a good reason to switch to GitLab as a primary repo, and then have everything mirrored to GitHub.

**Comment by ADRFranklin** [comment]
Actually I should point out that sampctl needs work doing as there are issues with using some repos even public ones from different repo hubs.

For example I self host a version of gitlab, where I host my libraries and personal projects and some of those libraries I include as a seperate repo for my gamemodes, and one of the issues I get is that sampctl reports the repo to be empty and requires me to manually do a `git clone` every time I ensure, build and run. 

So that is one of the issue you could run into.

**Comment by Southclaws** [comment]
I've never heard of that, can you open that as a separate issue with some details? I can't think why GitLab's git server is any different to others, there may be some subtleties that the Go implementation of Git isn't handling properly so it might even be an issue worth opening for that project too.

**Comment by hydewhyd** [comment]
Good, I mean for example when making a '_sampctl package init_' and ask the following:

> https://i.imgur.com/jzgXllK.png

The tool is assumed by default to work with Github without asking the user in which repository really wants to work.

Actually the tool has not asked us in which repository of code we want to work (github, gitlab, others ...), it would be good as a new implementation to be able to ask in which repository we want to work and for example in case GitLab is able to commit and more managements without the difficulty of having to be through other tools such as 'GitLab WorkFlow' or by configuring the SSH with difficulty.

**Comment by ADRFranklin** [comment]
Initially, sampctl was built with the idea of being used only with Github. Only later on in it's development cycle was it altered to support other repo hubs through (SSH/HTTPS) packages, though there is a big amount of code that still gives the idea that it is Github focused. We do plan to change this and give the user more choices in terms of repo hub releasing.

As you might already know `sampctl package release` only supports Github at this time, though we are planning to change all of this.

**Comment by Southclaws** [comment]
The `init` wizard does badly need an update to 1. not specifically say "GitHub" or have some better way of specifying the project "name" (identifier) 2. include all the new things like `local` etc.

The `release` command only uses GitHub for release creation, which is optional. Everything else is just standard Git tags. I may add support for GitLab releases *if there is significant demand*, otherwise it's just not worth the time. If these feature requests *do* grow, I'd rather abstract common functionality between GitHub and GitLab into another package (maybe this has already been done?).

Same with actual plugin binaries, no one seems to have any issues with GitHub so I don't see the value in supporting a whole new API unless there is significant demand (if only releases were Git-centric and standardised...)

**Comment by hydewhyd** [comment]
The way to expand more users to use sampctl is to expand the options and possibilities that sampctl can give us, not focusing only on that: "_if there is no demand, nothing will be done about it_".

I can think and some will think as if GitLab is supported, there will be more people who use the tool to use it in _private_ or _personal_ projects, not only in the public code publication of Github.

**Comment by Y-Less** [comment]
You can use it for private and personal projects already, adding GitLab doesn't add anything there.

**Comment by Southclaws** [comment]
> The way to expand more users to use sampctl is to expand the options and possibilities that sampctlcan give us, not focusing only on that: "if there is no demand, nothing will be done about it".

Please remember this is an open source voluntary work, if there's no good reason for me to spend time on it (i.e.: bringing value to people where I *know* the time will be worth it) then there's no reason for my to put the work in.

Of course, I will happily accept a PR that implements GitLab for release binaries if it's something you need.

**Comment by hydewhyd** [comment]
There is nothing more to discuss, perhaps someone else is interested in reopening it.

**Comment by Jeroen52** [comment]
You do you @hydewhyd, I use GitLab.
