### ISSUE TITLE
exit status 3221225781

### ISSUE THREAD

**Issue by Southclaws** [Southclaws/sampctl#282]
This needs to be documented and handled in a better way.

One way would be parsing arguments but if the compiler adds new arguments, this could become difficult to validate properly.

A simpler way would be to just add a nicer error message such as:

```
Invoking the compiler failed, please check your "args" configuration in your Package Definition File and validate that they are correct.
```

**Comment by maslag** [comment]
For future reference, I got this same error today when trying to set up a plugin development workspace with sampctl. 

I tried to run `sampctl p build --verbose` but I'd arrive at the same exit status. Since `--verbose` printed the path the compiler was being invoked from, I tried to run it directly via `cmd` but to no avail. 

Once I attempted to run the compiler from the Windows Explorer (i.e clicking on the icon) I was prompted with the error that `MSVCR100.dll` was missing. You need to install the [x86 2010 C redistributables](https://www.microsoft.com/en-us/download/confirmation.aspx?id=5555) to solve the problem 😃.

**Comment by wearLyS** [comment]
> For those of you discovering this issue via search, [this post](https://forum.sa-mp.com/showpost.php?p=4076874&postcount=51) details a way to debug the issue.

Help! The topic is down and I have this problem.

**Comment by backyardmonk** [comment]
> 
> 
> For future reference, I got this same error today when trying to set up a plugin development workspace with sampctl.
> 
> I tried to run `sampctl p build --verbose` but I'd arrive at the same exit status. Since `--verbose` printed the path the compiler was being invoked from, I tried to run it directly via `cmd` but to no avail.
> 
> Once I attempted to run the compiler from the Windows Explorer (i.e clicking on the icon) I was prompted with the error that `MSVCR100.dll` was missing. You need to install the [x86 2010 C redistributables](https://www.microsoft.com/en-us/download/confirmation.aspx?id=5555) to solve the problem 😃.

[Here's an updated link](https://www.microsoft.com/en-us/download/details.aspx?id=26999). It solved my issue on Windows 10.
