### ISSUE TITLE
Get name binaries from runtimes paths

### ISSUE THREAD

**Issue by pawnoholic** [Southclaws/sampctl#288]
@Southclaws , It would be nice to add the ability to run versions with a different binary file name. When package run a version CR-MP from runtimes, i get an error that the server binary file is not found.

I did something like this function, which requires revision:
```golang
func getServerBinary(platform, cacheDir, version string) (string) {
	pkg, err := FindPackage(cacheDir, version)
	if err != nil {
		return ""
	}
	
	want := ""
	
	switch platform {
	case "windows":
		want := pkg.Win32Paths
	case "linux", "darwin":
		want := pkg.LinuxPaths
	default:
		return ""
		
	return want
}
```

Need to parse want variable to get binary name.

**Comment by Southclaws** [comment]
I have wanted to do this for a long time to help CR-MP users. The problem is determining which entry in the map is the server binary. Currently that information isn't stored in the runtimes manifest so there's no way to know which file is which unless you are sure there's a common pattern such as the server always containing the sequence `svr`.

I could add that as a quick hack but I would not want to have that code long-term.

Anyway, this should work:

```go

func getServerBinary(platform, cacheDir, version string) (binary string) {
	pkg, err := FindPackage(cacheDir, version)
	if err != nil {
		return
	}

	var paths map[string]string
	switch platform {
	case "windows":
		paths = pkg.Win32Paths
	case "linux", "darwin":
		paths = pkg.LinuxPaths
	default:
		return
	}

	for source, destination := range paths {
		if strings.Contains(destination, "svr") {
			binary = destination
			break
		}
	}

	return
}
```
