### ISSUE TITLE
Stuck in package build. Not responding for 30 mins

### ISSUE THREAD

**Issue by iamcharles777** [Southclaws/sampctl#339]
commands: sudo sampctl package build --verbose

Is it required to have a repo? I manually copied my server files

`INFO: failed to open repo as git repository: repository not exists
INFO: samp/samp read package from directory /Library/WebServer/Documents/samp
INFO: samp/samp building dependency tree and ensuring cached copies
INFO: |- samp/samp is parent
INFO: |- iterating 0 dependencies of samp/samp
INFO: samp/samp flattened dependencies to 0 leaves
INFO: Checking for cached package pawn-v3.10.9-darwin.zip in /Users/samp/.samp
INFO: Using cached package pawn-v3.10.9-darwin.zip
INFO: using include path /Library/WebServer/Documents/samp/pawno/include
INFO: building samp/samp with 3.10.9
INFO: executing compiler in /Library/WebServer/Documents/samp/gamemodes as [LD_LIBRARY_PATH=/Users/samp/.samp/pawn/3.10.9 DYLD_LIBRARY_PATH=/Users/samp/.samp/pawn/3.10.9] [/Users/samp/.samp/pawn/3.10.9/pawncc /Library/WebServer/Documents/samp/gamemodes/gm.pwn -D/Library/WebServer/Documents/samp/gamemodes -o/Library/WebServer/Documents/samp/gamemodes/gm.amx -;+ -(+ -d3 -Z+ -i/Library/WebServer/Documents/samp/pawno/include MAX_PLAYERS=20]`

**Comment by Southclaws** [comment]
No, it's not required.

Check your system's process tree (procmon or task manager) to see if the compiler is actually running. If the compiler has frozen, it's unrelated to sampctl and you should open an issue on the compiler repo with a MVCE.

Otherwise, it might be an OS issue. Looks like a mac based on the directory paths, which removed x86 binary support a while back (Mojave I think) so the compiler might not work on that OS any more.

**Comment by iamcharles777** [comment]
Yeah Im using a Mojave.
That's sad news, I thought I can script on my mac .

**Comment by Southclaws** [comment]
You can try using Docker or a virtualbox VM.
