### ISSUE TITLE
Dependencies isn't downloaded, unknown warning

### ISSUE THREAD

**Issue by NeekoGta** [Southclaws/sampctl#407]
I get this when I execute `sampctl package ensure`.

Tester after reinstalled `sampctl`, deleted cache and dependencies folder.

`WARN: failed to ensure package github.com/sampctl/samp-stdlib: failed to ensure dependency from cache: pkt-line 1: invalid capabilities: arguments not allowed (multi_ack thin-pack side-band side-band-64k ofs-delta shallow deepen-since deepen-not deepen-relative no-progress include-tag multi_ack_detailed symref=HEAD:refs/heads/master object-format=sha1 agent=git/2.28.0.windows.1)
WARN: failed to ensure package github.com/sampctl/pawn-stdlib: failed to ensure dependency from cache: pkt-line 1: invalid capabilities: arguments not allowed (multi_ack thin-pack side-band side-band-64k ofs-delta shallow deepen-since deepen-not deepen-relative no-progress include-tag multi_ack_detailed symref=HEAD:refs/heads/master object-format=sha1 agent=git/2.28.0.windows.1)`

`sampctl` **still updated?** Southclaws has archived all these repositories related on SAMP. Hard.

**Comment by Pedrilkov** [comment]
The solution is to delete this library, the author abandoned it

**Comment by ADRFranklin** [comment]
This project is not abandoned, I still actively maintain it.

**Comment by ADRFranklin** [comment]
As for the issue, I also found this issue recently on Windows, and after reinstalling 1.9.1, it seems to have fixed it. Maybe you could do the same.

**Comment by Southclaws** [comment]
`invalid capabilities: arguments not allowed` is a Git server error. I wouldn't expect GitHub to throw that so I assume it's just a momentary issue on their end.

GitHub recently updated their auth services so that may have been the cause. I had to re-authenticate a few times.

What happens when you do any git operations over the network is the git client first asks the server what capabilities it has (Git has a lot of features, but not all servers/clients support them all). The client also sends its own capabilities to the server and the result is the intersection of these sets. If the set is empty or doesn't contain the capabilities that are required, then the client throws an error.
