### ISSUE TITLE
failed to parse packet as a dependency string: dependency string does not match pattern

### ISSUE THREAD

**Issue by Pedrilkov** [Southclaws/sampctl#411]
Who has a hand in the ass if you cannot do the same as in npm so that the file is created by itself and there are no problems at installation? How me and others should use your shit

**Comment by ADRFranklin** [comment]
This is not NPM, and you haven't given any information about how you are using sampctl to get this issue. I think the problem is your lack of reading the documentation, and therefore you have wrongfully specified a dependency field.

Don't insult tools, because you are not capable of reading the documentation.

**Comment by Southclaws** [comment]
Feel free to submit a pull request if you feel there are improvements that can be made 😊
