### ISSUE TITLE
[Windows] Can't build/run packages in WSL

### ISSUE THREAD

**Issue by EOussama** [Southclaws/sampctl#417]
Building and running packages always fails when used in WSL.

Project inside of a WSL instance
![image](https://user-images.githubusercontent.com/22644543/99159205-c680fc00-26da-11eb-9090-6ecd69ed586f.png)

Project on windows accessed via a WSL instance
![image](https://user-images.githubusercontent.com/22644543/99159125-14e1cb00-26da-11eb-84d6-bc998b7efff3.png)

**Comment by ADRFranklin** [comment]
This is not specific to WSL2, as I am using it in WSL2 just fine, and this issue has occurred on production systems running the full Ubuntu OS.

The issue is specific to the compiler and not sampctl, there is nothing we can do to help here. I would advise using another version of the compiler, or try to make an issue there.

**Comment by se8870** [comment]
If your WSL is 64 bit, you may read my issues below:
https://github.com/Southclaws/sampctl/issues/406#issuecomment-681194736

**Comment by EOussama** [comment]
> If your WSL is 64 bit, you may read my issues below:
> [#406 (comment)](https://github.com/Southclaws/sampctl/issues/406#issuecomment-681194736)

That did the trick, thank you very much.
