### ISSUE TITLE
doesn't seem to support directories name with spaces?

### ISSUE THREAD

**Issue by PatrickGTR** [Southclaws/sampctl#45]
I maybe wrong as I just began using samp ctl and realised, how useful it was!

Title says so^

**Input**
``
C:\Users\Patrick>sampctl server init --dir E:\PAWN\San Andreas Multiplayer\
``

**Output as**
``
C:\Users\Patrick>sampctl server init --dir E:\PAWN\San\
``

therefore showing the error
``Exited with error: failed to initialise server: open E:\Developer\San\samp\samp.json: The system cannot find the path specified.``

EDIT: Just wondering so instead of pressing compile F5 to compile on your Text Editor, I just run sampctl package build? is there any work around to compile it using sampctl when F5 is pressed for example?

**Comment by PatrickGTR** [comment]
ignore the long directories on title, I've changed it back, it was a mistake from ;) though the spacing is still an issue.

**Comment by Southclaws** [comment]
This is a common issue with all command line apps, flags are parsed by using spaces as a delimiter so there's no real way to get around this without trying to be clever.

But I don't maintain the command-line library that this tool uses (urfave/cli). The standard way of solving this is to just enclose the entire value in quotes:

`C:\Users\Patrick>sampctl server init --dir "E:\PAWN\San Andreas Multiplayer\"`

However, I haven't tested quoted input so that's something I'll add to the unit tests, thanks!

One final thing: you don't necessarily need to use `--dir`, I only added it for rare circumstances. You can actually just `cd` into your directory and run `sampctl server init`:

```ps
E:
cd "PAWN/San Andreas Multiplayer"
sampctl server init
```
(note that `E:` is to change your active drive on Windows)

**Comment by Southclaws** [comment]
Tested on osx, works with quotes:

```bash
southclaws@corax ~/go/src/github.com/Southclaws/sampctl
∆ $ mkdir "temp with space"

southclaws@corax ~/go/src/github.com/Southclaws/sampctl
∆ $ ./sampctl server init --dir "temp with space"
This directory does not appear to have a gamemodes directory, you must add at least one gamemode to run a server
This directory does not appear to have a filterscripts directory
This directory does not appear to have a plugins directory
? Server Hostname Name
```

**Comment by Southclaws** [comment]
If you can confirm quotes work fine on Windows too (I don't see why they wouldn't) that would be great!

**Comment by PatrickGTR** [comment]
Yeah, quotation marks seems to be the work around. Closed :)


```
C:\Users\Patrick>sampctl server init --dir "E:PAWN\samp ctl"
This directory does not appear to have a gamemodes directory, you must add at least one gamemode to run a server
This directory does not appear to have a filterscripts directory
This directory does not appear to have a plugins directory
? Server Hostname yes
? RCON Password (leave blank to generate a strong one)
? Server Port 7777
? Max Players 32
Hostname:  yes
RCONPassword:  ;:MiNj397;?;  complexity score:  centuries
Port:  7777
Gamemodes:  []
Filterscripts:  []
Plugins:  []
Using cached package for 0.3.7
```

```E:\PAWN\samp ctl>dir
 Volume in drive E has no label.
 Volume Serial Number is BCE7-DB3C

 Directory of E:\PAWN\samp ctl

04/12/2017  13:35    <DIR>          .
04/12/2017  13:35    <DIR>          ..
04/12/2017  13:35            40,960 announce.exe
04/12/2017  13:35           282,624 samp-npc.exe
04/12/2017  13:35           950,272 samp-server.exe
04/12/2017  13:35                90 samp.json
               4 File(s)      1,273,946 bytes
               2 Dir(s)  690,814,992,384 bytes free

E:\PAWN\samp ctl>
```
