### ISSUE TITLE
Not working when installing crashdetect

### ISSUE THREAD

**Issue by lucasgama335** [Southclaws/sampctl#471]
When we try to install or crashdetect:

`sampctl package install Zeex/samp-plugin-crashdetect`
or
`sampctl package ensure`

the following error occurs:
`WARN: Failed to guarantee package github.com/Zeex/samp-plugin-crashdetect:v4.20: remote repository is empty`
`WARNING: Failed to secure package github.com/Zeex/samp-plugin-crashdetect:v4.20: remote repository is empty`
`WARNING: Failed to secure package github.com/Zeex/samp-plugin-crashdetect:v4.20 after 2 tries, skipping`

I've already tried in other gamemodes that use sampctl and starting a project from the beginning, the same error always occurs.
I also tried installing previous versions of the plugin but the error remains

**Comment by ADRFranklin** [comment]
Try deleting your `sampctl` folder from the appdata folder on windows or the `~/.config/sampctl` on linux. Generally this problem happens either because the remote server returned an empty repository, or you partially downloaded a repository and not enough information was downloaded for git to work with it, or the repository is corrupt. 

The only solution is to try delete the packages folder or delete the entire cache folder allowing a fresh pull of the repositories. If that still fails, then there seems to be a problem with downloading the repository, which won't be sampctl's fault and will be something else causing it.

**Comment by lucasgama335** [comment]
deleting the cache folder worked again.  thanks!
