### ISSUE TITLE
Error: formulae require at least a URL

### ISSUE THREAD

**Issue by ALF-ONE** [Southclaws/sampctl#491]
~ % brew install Southclaws/sampctl/sampctl
Error: formulae require at least a URL
/opt/homebrew/Library/Homebrew/formula.rb:283:in `determine_active_spec'
/opt/homebrew/Library/Homebrew/formula.rb:214:in `initialize'
/opt/homebrew/Library/Homebrew/formulary.rb:308:in `new'
/opt/homebrew/Library/Homebrew/formulary.rb:308:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:469:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:561:in `factory'
/opt/homebrew/Library/Homebrew/cli/parser.rb:636:in `block in formulae'
/opt/homebrew/Library/Homebrew/cli/parser.rb:632:in `map'
/opt/homebrew/Library/Homebrew/cli/parser.rb:632:in `formulae'
/opt/homebrew/Library/Homebrew/cli/parser.rb:308:in `parse'
/opt/homebrew/Library/Homebrew/cmd/install.rb:147:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:98:in `<main>'

**Comment by doraketa** [comment]
@ALF-ONE 

Good afternoon, I ran into a similar problem... Has the solution appeared?

**Comment by doraketa** [comment]
> I don't think it makes sense to use sampctl on mac anymore, since 32bit support was removed, you can't build with the compiler anyway, so you are better off using docker or a vm to build with.

 Thank you for feedback! Yes, i think, this problem connected with my architecture... It's too bad. But your idea - is very good, and i continue my development with docker image.

**Comment by Southclaws** [comment]
What's happening here is the Brew config for this project is restricted to only Intel architectures. This is because none of sa-mp's legacy binaries or open.mp's current binaries are compiled for any Arm architectures. The part of the config causing this error is `if Hardware::CPU.intel?` (I'm not really sure why Brew doesn't provide a proper helpful error message for this...)

https://github.com/Southclaws/sampctl/blob/master/sampctl.rb#L10-L19

Now, while it _is_ possible for Pawn, open.mp and modern plugins to be compiled for Arm, there's simply no real demand for this from the community right now. It would be quite an effort to get official Arm support moving across the ecosystem, not impossible but it would require significant demand from developers.
