### ISSUE TITLE
Build fails on dependencyless package

### ISSUE THREAD

**Issue by Y-Less** [Southclaws/sampctl#76]
```
PS D:\work\SA-MP\pawno\include\amx_assembly> sampctl package ensure
INFO: ensured dependencies for package
PS D:\work\SA-MP\pawno\include\amx_assembly> sampctl package build
failed to resolve dependencies before build: no local dependencies present, must ensure dependencies first
PS D:\work\SA-MP\pawno\include\amx_assembly>
```

**Comment by Y-Less** [comment]
I think a better solution is to always create the directory.  From looking at the code, I think the `dependencies` directory is implicitly created when you check out a git repository.  If no repositories are checked out the directory isn't created.  Then when you build it thinks you haven't ensured first.  Instead, create the directory manually then do the checkouts (if there are any).  This ensures people always ensure first (since they may not know there are no dependencies), and enforces it by keeping the error at build time.  I was going to do that as a fix, but don't know Go yet (I'm sure looking up how to create a directory can't be hard, but I also can't build this right now).

**Comment by Southclaws** [comment]
I was thinking of that, but it seems to be strange to have a `dependencies` folder implicitly created for no dependencies. Not that it really matters as I doubt there would really be any packages with *no* dependencies - unless they are purely macro packages I suppose...

For now, I've just removed the actual error raised by the ResolveDependencies function so it just returns if there is no dependencies. I did this because the EnsureDependencies function is only called by Build if forceBuild (--forceBuild) is true.
