### ISSUE TITLE
Generate LICENSE

### ISSUE THREAD

**Issue by Y-Less** [Southclaws/sampctl#91]
```> **IMPORTANT**: Modify `LICENSE` with your preferred license text.```

Could this be generated?  Give an option in the wizard to select from a few common choices (MIT, MPL 1.0/2.0, GPL, etc), and insert the name and year in to templates.

**Comment by Southclaws** [comment]
That note is left over from the [pawn-package-template](https://github.com/Southclaws/pawn-package-template) repo, that contains a MIT license by default. I haven't gotten around to adding a license option in the init wizard yet...

Some licenses require the addition of a comment block to each source file and that comment block is the actual part that includes the name/year rather than the LICENSE file itself.

I'll have a think about this a bit more as it's not as trivial as I first thought! GitHub actually provide a license API: https://developer.github.com/v3/licenses/ but it doesn't support template replacements of any sort (new side project...?).

Going back to the per-file thing, maybe it would be nice to have a "license ensure" command, so when you add a new module to a large library, you can quickly shove a license block in it...?
