### ISSUE TITLE
Build results

### ISSUE THREAD

**Issue by Dayvison** [Southclaws/sampctl#99]
I think will be better:
- Show a error message instead of a info on builds fails.
- Show the info about build(header, code, data, stack/heap, estimated and total) only if the flags `-d2`, `-d3` or -v2 has activated #49

With this will be:
```
ERROR: Build complete with 1 problems                                                             
```

**Comment by Dayvison** [comment]
* Show only the path after workingDir
* Show the correct the paths, remove symlinks

This will be:
```
dependencies/YSI-Includes/YSI_Data/y_iterate.inc:00 (warning) **
source/main.pwn:00 (warning) **
```
Instead
```
/home/user/path/to/dependencies/YSI-Includes/YSI\..\YSI_Data\y_iterate.inc:00 (warning) **
/home/user/path/to/source/main.pwn:00 (warning) **
```

**Comment by Y-Less** [comment]
The path resolution seems like it would be more useful in the compiler itself, so that we get nicer error paths with or without sampctl.

**Comment by Y-Less** [comment]
Cutting the start off is a more opinionated change so should probably just stay here.

**Comment by Dayvison** [comment]
I already do this, but the sampctl join the absolute path here:
https://github.com/Southclaws/sampctl/blob/c7ae3b837bfb980c5dee4a6a43be35ec65fe671e/compiler/compiler.go#L183-L187

**Comment by Southclaws** [comment]
There's a lot on this issue so I'll address each part, in future it's best to open *separate* issues for different suggestions/reports.

> Show a error message instead of a info on builds fails.

Yes this would make sense to use error semantics, I'll take a look at this.

> Show the info about build

I'm not so sure about this, it's only one line and it may or may not be useful. It could warrant a separate config setting for builds though (not -d3) or just use the `--verbose` printer.

> Show only the path after workingDir

There's an issue open for this already on the compiler repo: https://github.com/Southclaws/pawn/issues/247 the problem is inconsistency with the compiler outputting paths so sampctl resolves this by making everything absolute. Relative could make sense though if the working directory is above `dependencies/` because I'd prefer to avoid `../` jumps in paths to keep things concise. 99% of the time, users won't be including things outside of their project directory unless they use `builds.*.includes` instead of `dependencies` for their includes.

> Show the correct the paths, remove symlinks

Do you have any examples of *incorrect* paths?

I've not dealt with symlinks either so I'll have to test and implement support for that. I didn't even consider it!

**Comment by Dayvison** [comment]
I mean the YSI symlinks,

`/home/user/path/to/dependencies/YSI-Includes/YSI\..\YSI_Data\y_iterate.inc:00 (warning) **`
I solved this using
```diff
diff --git a/compiler/compiler.go b/compiler/compiler.go
index e9a918a..707a553 100644
--- a/compiler/compiler.go
+++ b/compiler/compiler.go
@@ -180,10 +180,17 @@ func CompileWithCommand(cmd *exec.Cmd, workingDir string) (problems types.BuildP
 
 				problem := types.BuildProblem{}
 
+				if string(filepath.Separator) != "\\" {
+					problem.File = filepath.Clean(strings.Replace(groups[1], "\\", "/", -1))
+				}
```

**Comment by Y-Less** [comment]
Be warned that YSI uses both `\\` and `/` for different uses:

https://github.com/pawn-lang/YSI-Includes/wiki/Include-Guards

`\\` is the officially correct way to include YSI libraries, anything else may cause problems.

**Comment by Y-Less** [comment]
I don't know if you are talking pre- or post-compile though.

**Comment by Dayvison** [comment]
I'm just take YSI as a example, but i know the diference between `\` and `/`.

In the example this output from compiler.
`YSI-Includes/YSI\..\YSI_Data\y_iterate.inc:00 (warning) **`
Will become
`YSI-Includes/YSI_Data/y_iterate.inc:00 (warning) **`

**Comment by Southclaws** [comment]
Ah, I did forget about that. It makes sense to normalise path separators on the build output to use one path separator.

**Comment by Y-Less** [comment]
> I'm just take YSI as a example, but i know the diference between \ and /.

Good, just checking.
